# Generated by Django 3.2 on 2021-04-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameStudent', models.CharField(max_length=20, verbose_name='Имя стдента')),
                ('familyStudent', models.CharField(max_length=20, verbose_name='Фамилия студента')),
                ('averageScore', models.IntegerField(verbose_name='Средний балл')),
            ],
        ),
    ]
